common-obj-y += pci.o
common-obj-y += pci_bridge.o
common-obj-y += msix.o msi.o
common-obj-y += shpc.o
common-obj-y += slotid_cap.o
common-obj-y += pci_host.o pcie_host.o
common-obj-y += pcie.o pcie_aer.o pcie_port.o
